# Generated by Django 3.0.2 on 2020-10-03 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('bill', models.ImageField(upload_to='bill/')),
                ('expenses_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.ExpensesCategory')),
            ],
            options={
                'db_table': 'expenses',
            },
        ),
    ]
